services:
  
  linux:
    container_name: base_linux4
    image: ubuntu:24.04
  php:
    container_name: webserver-wp4
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./php_code:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
  mysql:
    image: mysql:8.4
    container_name: mysql-wp4
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:7.4
    container_name: redis-wp4
    ports:
      - 6379:6379

  django:
    container_name: prepare_lms4
    build: .
    volumes:
      - ./code:/code
    ports:
      - "8001:8000"
    # command: sleep infinity
    command: python manage.py runserver 0.0.0.0:8000
  postgres:
    container_name: prepare_db4
    image: postgres:16
    environment:
      - POSTGRES_DB=simple_lms
      - POSTGRES_USER=simple_user
      - POSTGRES_PASSWORD=simple_password
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5551:5432"

volumes:
  mysql_data:
  postgres_data: